version: '3'
services:
  frontend:
    build: ./vue-antdesign-todolist
    restart: always
    hostname: vue-antdesign-todolist
    networks:
      - frontnet
    ports:
      - "8083:8083"
  backend:
    build: ./nest-postgres-todolist
    restart: always
    hostname: nest-postgres-todolist
    env_file:
      - .env
    networks:
      - frontnet
      - backnet
    ports:
      - "8080:8080"
  db:
    image: 'postgres'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - "/home/kutman/docker/postgres/data:/var/lib/postgresql/data"
    networks:
      - backnet
    ports:
      - "5432:5432"
  elasticsearch:
    restart: always
    image: elasticsearch:7.8.1
    container_name: elasticsearch
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    network_mode: "host"

    kibana:
      restart: always
      image: kibana:7.8.1
      container_name: kibana
      environment:
        XPACK_SECURITY_ENABLED: 'true'
        ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_NODE}
        ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
        ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      network_mode: "host"

volumes:
  elastic-data:
    driver: local

networks:
  backnet:
  frontnet:
